### ISSUE TITLE
Unknown cause issues

### ISSUE THREAD

**Issue by ArnoFanrce** [FrostbyteGames1/Frostbytes-Improved-Inventory#25]
![2024-07-25_10 47 16](https://github.com/user-attachments/assets/63f46575-ace3-47cf-b520-e46820a53a56)
Using this mod will result in a completely white field of view, and I'm not sure what conflicts with it, but it won't crash
[latest.log](https://github.com/user-attachments/files/16369734/latest.log)

**Comment by sloweia** [comment]
same

**Comment by FrostbyteGames1** [comment]
If you are experiencing this bug in Minecraft 1.20.6, it should now be resolved by v1.8.6.

**Comment by sloweia** [comment]
Still occurs on 1.20.6
[latest.log](https://github.com/user-attachments/files/16422378/latest.log)

**Comment by lanwoodall423** [comment]
I'm having this issue on 1.20.1

**Comment by FrostbyteGames1** [comment]
Out of curiosity, what does the game say that FOV is set to when this mod is installed?
